### ISSUE TITLE
Receives but won't send texts

### ISSUE THREAD

**Issue by RobNuts** [iHelp101/VoicePlus#1]
Seems to be receiving texts in other apps if I set them to default messaging app. But it took 20 minutes for the text to arrive and it won't send messages. Only receive it seems.

Samsung Galaxy S3 Verizon SCH-I535
CM version 12.1-20151117-SNAPSHOT-YOG7DAO1K7-d2vzw
Android 5.1.1

**Comment by iHelp101** [comment]
Interesting, the default messaging app issue is normal. The text arrival sounds like push notifications are being delayed, which usually depends on connection. Are you seeing the text arrive to the Google Voice app and then take 20 minutes? Or is it 20 minutes to get to the Google Voice app?

I will look into the sending issue.

**Comment by RobNuts** [comment]
I'm testing by sending a text from the web with Textnow. Just sent one right now. GV app received the notification immediately. Ok this time it took 3 minutes to receive it in the default app. Not sure but seemed to receive it as soon as I opened the Voiceplus app. Does it only check for msgs every 15 minutes? Or should it receive them as soon as they are supposed to be received? Perhaps it's not staying running in the background. I'll check any app hibernaters I have installed and make sure it's whitelisted. And what did you mean by "the default messaging app is normal"?

**Comment by iHelp101** [comment]
The module does not do any checking. The module hooks into Google Voice when it gets a message. It gets that message and creates a fake SMS broadcast using "android.permission.RECEIVE_SMS". This message is only sent to the default messaging app in Android 4.4+.

**Comment by RobNuts** [comment]
By checking I was referring to the polling option. Anyhow I added the apps to whitelists and disabled the two hibernaters I had and now the default sms app is receiving the texts almost immediately. So the lag problem was on my end. Just need to get sending/replying to work.

**Comment by iHelp101** [comment]
The syncing setting gets text from other devices. So if you for example use Google Voice on your desktop, it will sync the message you sent on your desktop with your device. I am testing a possible fix.

**Comment by RobNuts** [comment]
Well. I hope I didn't waste your time. My default sms app appears to be sending sms as well now. Not sure why it would receive but not send earlier. Perhaps voiceplus ran long enough to receive but then got killed in the background when trying to reply. I'm assuming this won't work if I update to CM 13 Marshmallow?
